frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"
      - any-glob-to-any-file: ".github/**"

repo:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "LICENSE"
          - ".coderabbit.yaml"
          - "package.json"
          - "bun.lock"
          - "mise.toml"
          - ".oxfmtrc.json"
          - ".oxlintrc.json"
          - ".eslintignore"
          - ".gitignore"
